name: guardian_app
description: تطبيق الأمين الشرعي - نسخة الموبايل
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  google_fonts: ^6.2.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  image_picker: ^1.0.7
  hijri: ^3.0.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
